version: '3'
services:
  dante:
    build: .
    ports:
      - "1080:1080"
    logging:
      options:
        tag: dante
    restart: unless-stopped
    tmpfs: /tmp
    read_only: true
  dante_users:
    build:
      context: .
      args:
        with_users: 'true'
    ports:
      - "1081:1080"
    logging:
      options:
        tag: dante
    restart: unless-stopped
    tmpfs: /tmp
    read_only: true
  dante_all_networks:
    build:
      context: .
      args:
        with_users: 'true'
        all_networks: 'true'
    ports:
      - "1082:1080"
    logging:
      options:
        tag: dante
    restart: unless-stopped
    tmpfs: /tmp
    read_only: true
  dante_yolo:
    build:
      context: .
      args:
        all_networks: 'true'
    ports:
      - "1083:1080"
    logging:
      options:
        tag: dante
    restart: unless-stopped
    tmpfs: /tmp
    read_only: true
